
# UI CONSTANTS

HEIGHT = 800
WIDTH = 1000
EDITOR_WIDTH = WIDTH // 4
EDITOR_HEIGHT = HEIGHT // 2
BUTTON_WIDTH = 100
BUTTON_HEIGHT = 20
RAM_WIDTH = WIDTH//2
RAM_HEIGHT = RAM_WIDTH
RAM_CELL_WIDTH = RAM_WIDTH // 10
RAM_CELL_HEIGHT = RAM_HEIGHT // 40



# ASSEMBLER CONSTANTS

RAM_SIZE = 100
RAM_CELL_MEM_SIZE = 11
MAX_MEM_VALUE =  (2 ** RAM_CELL_MEM_SIZE) - 1  # 2s comp - max positive one less than unsigned
MIN_MEM_VALUE = 0 - (MAX_MEM_VALUE + 1)        # 2s comp - min negative == log(2)
OPCODE_DIGS = 2
OPERAND_DIGS = 3